---
  deployments:
    tasks:
      - export DEPLOY_PATH=/home/ilxabzuaup05/public_html/
      - /bin/cp index.html $DEPLOY_PATH
    # script:
      # - npm install
      # - npm run build
      # - cp -a dist/. public/
    # artifacts:
      # paths:
        # - public

